services:
  acestream:
    build: 
      context: .    
    container_name: docker-acestream    
    ports:
      - 6878:6878
    dns:
      - 1.1.1.1
      - 8.8.8.8  
    environment:
      - INTERNAL_IP=127.0.0.1
      - HTTP_PORT=6878
      - HTTPS_PORT=6879
networks:
  default:
    driver: bridge
